// Define the structure of our preset items
type PresetItems = {
  names: string[][];
  date: string[];
  movie: string[];
  bottle: string[];
  truth: string[];
  dinner: string[];
  workout: string[];
  team: string[];
  chorus: string[];
};

export type PresetKey = keyof PresetItems;

const PRESETS: { key: PresetKey; label: string; emoji: string }[] = [
  { key: "names", label: "List of names", emoji: "👥" },
  { key: "date", label: "Ideas for date night", emoji: "✨" },
  { key: "movie", label: "Movie night", emoji: "🎬" },
  { key: "bottle", label: "Spin the bottle", emoji: "🍾" },
  { key: "truth", label: "Truth or dare", emoji: "🎯" },
  { key: "dinner", label: "What’s For Dinner", emoji: "🍽️" },
  { key: "workout", label: "Workout Program", emoji: "🏋️" },
  { key: "team", label: "Team Building Games", emoji: "🤝" },
  { key: "chorus", label: "Chores Wheel", emoji: "🎼" },
];

const PRESET_ITEMS = {
  names: [
   [ 
    "Lia",
   "Noah",
   "William",
   "James",
   "Oliver",
   "Elijah",
   "Benjamin",
   "Lucas",
   "Henry",
   "Elexander",
   "Ethan",
   "Jack",
   "Michael",
   "Daniel",
   "Jacob",
   "Logan",
   "Jackson",
   "Levi",
   "Sebastian",
   "Mateo",
   "Owen",
   "Theodore",
   "Aiden",
   "Samuel",
   "Joseph",
   "John",
   "David",
   "Wyatt",
   "Matthew",
   "Luke",
   "Asher",
   "Carter",
   "Julian",
   "Grayson",
   "Leo",
   "Jayden",
   "Gabriel",
   "Isaac",
   "Lincoln",
   "Anthony",
   "Hudson",
   "Dylan",
   "Ezra",
   "Thomas",
   "Charles",
   "Christopher",
   "Jaxon",
   "Maverick",
   "Josiah",
   "Isaiah",
   "Andrew",
   "Elias",
   "Joshua",
   "Nathan",
   "Caleb",
   "Ryan",
   "Adrian",
   "Miles",
   "Eli",
   "Nolan",
   "Christian",
   "Aaron",
   "Cameron",
   "Ezekiel",
   "Colton",
   "Luca",
   "Landon",
   "Hunter",
   "Jonathan",
   "Santiago",
   "Axel",
   "Easton",
   "Cooper",
   "Jeremiah",
   "Angel",
   "Roman",
   "Connor",
   "Jameson",
   "Robert",
   "Greyson",
   "Jordan",
   "Ian",
   "Carson",
   "Jaxson",
   "Leonardo",
   "Nicholas",
   "Dominic",
   "Austin",
   "Everett",
   "Brooks",
   "Xavier",
   "Kai",
   "Jose",
   "Parker",
   "Adam",
   "Jace",
   "Wesley",
   "Kayden",
   "Silas",
   "Bennett",
   "Declan", 
   "Waylon", 
   "Weston", 
   "Evan", 
   "Emmett", 
   "Micah", 
   "Ryder", 
   "Beau", 
   "Damian", 
   "Brayden", 
   "Gael", 
   "Rowan", 
   "Harrison", 
   "Bryson", 
   "Sawyer", 
   "Amir", 
   "Kingston", 
   "Jason", 
   "Giovanni", 
   "Vincent", 
   "Ayden", 
   "Chase", 
   "Myles", 
   "Diego", 
   "Nathaniel", 
   "Legend", 
   "Jonah", 
   "River", 
   "Tyler", 
   "Cole", 
   "Braxton", 
   "George", 
   "Milo", 
   "Zachary", 
   "Ashton", 
   "Luis", 
   "Jasper", 
   "Kaiden", 
   "Adriel", 
   "Gavin", 
   "Bentley", 
   "Calvin", 
   "Zion", 
   "Juan", 
   "Maxwell", 
   "Max", 
   "Ryker", 
   "Carlos", 
   "Emmanuel", 
   "Jayce", 
   "Lorenzo", 
   "Ivan", 
   "Jude", 
   "August", 
   "Kevin", 
   "Malachi", 
   "Elliott", 
   "Rhett", 
   "Archer", 
   "Karter", 
   "Arthur", 
   "Luka", 
   "Elliot", 
   "Thiago", 
   "Brandon", 
   "Camden", 
   "Justin", 
   "Jesus", 
   "Maddox", 
   "King", 
   "Theo", 
   "Enzo", 
   "Matteo", 
   "Emiliano", 
   "Dean", 
   "Hayden", 
   "Finn", 
   "Brody", 
   "Antonio", 
   "Abel",
   "Alex",
   "Tristan",
   "Graham",
   "Zayden",
   "Judah",
   "Xander",
   "Miguel",
   "Atlas",
   "Messiah",
   "Barrett",
   "Tucker",
   "Timothy",
   "Alan",
   "Edward",
   "Leon",
   "Dawson",
   "Eric",
   "Ace",
   "Victor",
   "Abraham",
   "Nicolas",
   "Jesse",
   "Charlie",
   "Patrick",
   "Walker",
   "Joel",
   "Richard",
   "Beckett",
   "Blake",
   "Alejandro",
   "Avery",
   "Grant",
   "Peter",
   "Oscar",
   "Matias",
   "Amari",
   "Lukas",
   "Andres",
   "Arlo",
   "Colt",
   "Adonis",
   "Kyrie",
   "Steven",
   "Felix",
   "Preston",
   "Marcus",
   "Holden",
   "Emilio",
   "Remington",
   "Jeremy",
   "Kaleb",
   "Brantley",
   "Bryce",
   "Mark",
   "Knox",
   "Israel",
   "Phoenix",
   "Kobe",
   "Nash",
   "Beckham", 
   "Derek", 
   "Crue", 
   "Jett", 
   "Paxton",   
   "Malakai", 
   "Cash", 
   "Kaden", 
   "Gianni", 
   "Rafael", 
   "Maximiliano", 
   "Simon", 
   "Caden", 
   "Brady", 
   "Zane", 
   "Emerson", 
   "Reid", 
   "Jake", 
   "Colin", 
   "Dallas", 
   "Milan", 
   "Andre", 
   "Erick", 
   "Walter", 
   "Chance", 
   "Cohen", 
   "Brian", 
   "Tobias", 
   "Cody", 
   "Tanner", 
   "Francisco", 
   "Clayton", 
   "Donovan", 
   "Rory", 
   "Shawn", 
   "Hendrix", 
   "Spencer", 
   "Gideon", 
   "Stephen", 
   "Manuel", 
   "Karson", 
   "Raymond", 
   "Reed", 
   "Clark", 
   "Andy", 
   "Wade", 
   "Eduardo", 
   "Fernando", 
   "Mario", 
   "Landen", 
   "Travis", 
   "Knoxley", 
   "Zander", 
   "Maximo", 
   "Troy", 
   "Kameron", 
   "Cesar", 
   "Garrett", 
   "Ellis", 
   "Holden", 
   "Reese", 
   "Kade", 
   "Kyson", 
   "Shane", 
   "Dillon", 
   "Clay", 
   "Cruz", 
   "Bo", 
   "Boston"
  ],
 [
 "Olivia",
 "Emma",
 "Charlotte",
 "Amelia",
 "Sophia",
 "Isabella",
 "Ava",
 "Mia",
 "Evelyn",
 "Harper",
 "Luna",
 "Camila",
 "Gianna",
 "Elizabeth",
 "Eleanor",
 "Ella",
 "Abigail",
 "Sofia",
 "Avery",
 "Scarlett",
 "Emily",
 "Aria",
 "Penelope",
 "Chloe",
 "Layla",
 "Mila",
 "Nora",
 "Hazel",
 "Nova",
 "Lily",
 "Isla",
 "Grace",
 "Violet",
 "Aurora",
 "Riley",
 "Zoey",
 "Willow",
 "Emilia",
 "Stella",
 "Zoe",
 "Victoria",
 "Hannah",
 "Addison",
 "Leah",
 "Lucy",
 "Eliana",
 "Ivy",
 "Everly",
 "Lillian",
 "Paisley",
 "Elena",
 "Naomi",
 "Maya",
 "Natalie",
 "Kinsley",
 "Delilah",
 "Claire",
 "Audrey",
 "Aaliyah",
 "Ruby",
 "Brooklyn",
 "Alice",
 "Aubrey",
 "Autumn",
 "Leilani",
 "Savannah",
 "Valentina",
 "Kennedy",
 "Madison",
 "Eleanor",
 "Josephine",
 "Bella",
 "Skylar",
 "Genesis",
 "Hailey",
 "Sadie",
 "Gabriella",
 "Allison",
 "Anna",
 "Serenity",
 "Nevaeh",
 "Cora",
 "Ariana",
 "Emery",
 "Lydia",
 "Jade",
 "Sarah",
 "Eva",
 "Adeline",
 "Madelyn",
 "Piper",
 "Rylee",
 "Athena",
 "Peyton",
 "Everleigh",
 "Vivian",
 "Clara",
 "Raelynn",
 "Liliana",
"Samantha",
"Maria",
"Iris",
"Ayla",
"Eden",
"Eliza",
"Rose",
"Melody",
"Isabelle",
"Mary",
"Freya",
"Margaret",
"Brynn",
"Remi",
"Reagan",
"Valeria",
"Charlie",
"Amara",
"Melanie",
"Gabrielle",
"Alexandra",
"Natalia",
"Lauren",
"Jasmine",
"Ariella",
"Morgan",
"Harmony",
"Alexis",
"Jordyn",
"Andrea",
"Alina",
"Bailey",
"Dakota",
"Elsie",
"London",
"Ny",
"Catalina",
"Katherine",
"Olive",
"Emerson",
"Adalynn",
"Faith",
"Madeline",
"Brielle",
"Rosalie",
"Emersyn",
"Blakely",
"Kimberly",
"Esther",
"Ariel",
"Valerie",
"Aspen",
"Norah",
"Alyssa",
"Eloise",
"Ellie",
"Sloane",
"Amira",
"Juliana",
"Ruth",
"Brianna",
"Delaney",
"Rebecca",
"Izabella",
"Georgia",
"Alaina",
"Michelle",
"Anastasia",
"Noelle",
"Genevieve",
"Caroline",
"Cecilia",
"Ember",
"Juniper",
"Kayla",
"Aubree",
"Margot",
"Adalyn",
"Arya",
"Leighton",
"Taylor",
"Molly",
"Laila",
"Paige",
"Lila",
"Kenzie",
"Tatum",
"Finley",
"Daisy",
"Brooke",
"Rachel",
"Gracie",
"Joy",
"Presley",
"Sienna",
"Stephanie",
"Wren",
"Adriana",
"Alayna",
"Elise",
"Lyla",
"Arabella",
"Fiona",
"Phoebe",
"Vanessa",
"Adelaide",
"Gemma",
"Makenna",
"Jane",
"Cali",
"Kailani",
"Camille",
"Emory",
"Ryleigh",
"Amina",
"Jordan",
"Maggie",
"Lucia",
"Blake",
"Ana",
"Haven",
"Elle",
"Lennon",
"Callie",
"Hope",
"Amaya",
"Alison",
"Sage",
"Julianna",
"Dahlia",
"Zara",
"Camilla",
"Raegan",
"Vera",
"Annie",
"Carmen",
"Haley",
"Nina",
"Daisy",
"Evangeline",
"Kate",
"Alicia",
"Skyler",
"Riley",
"Maren",
"Summer",
"Amari",
"Joanna",
"Heaven",
"Kendra",
"Selena",
"Celeste",
"Maci",
"Paris",
"Amber",
"Arianna",
"Sierra",
"Kenzie",
"Lana",
"Briar",
"Lainey",
"Adelynn",
"Ivory",
"Mariana",
"Cataleya",
"Rosemary",
"Maisie",
"Talia",
"Skye",
"Lacey",
"Kyla",
"Annalise",
"Alana",
"Cassidy",
"Mabel",
"Charlee",
"Journey",
"Miriam",
"Sawyer",
"Kylie",
"Adrianna",
"Rosie",
"Blair",
"Oaklynn",
"Carly",
"Marlee",
"Rory",
"Elliana",
"Alexandria",
"Serena",
"Kora",
"Ainsley",
"Fern",
"Adley",
"Lillie",
"Colette",
"Felicity",
"Kassidy",
"Aspen",
"Faith",
"Giuliana"
 ],

[
"Avery",
  "Riley",
  "Jordan",
  "Rowan",
  "Peyton",
  "Harper",
  "Quinn",
  "Emerson",
  "Sawyer",
  "Parker",
  "Taylor",
  "Charlie",
  "Reese",
  "Finley",
  "Rylan",
  "Eden",
  "Morgan",
  "River",
  "Hayden",
  "Dakota",
  "Skyler",
  "Cameron",
  "Elliot",
  "Blake",
  "Emery",
  "Lennon",
  "Phoenix",
  "Remi",
  "Alex",
  "Tatum",
  "Sage",
  "Arden",
  "Casey",
  "Kendall",
  "Ariel",
  "Logan",
  "Rory",
  "Ainsley",
  "Skylar",
  "Jamie",
  "Marley",
  "Raven",
  "Sutton",
  "Ellis",
  "Rowe",
  "Greer",
  "Shiloh",
  "Terry",
  "Harlow",
  "Aubrey",
  "Jules",
  "Hollis",
  "Monroe",
  "Linden",
  "Oakley",
  "Bailey",
  "Winter",
  "Sailor",
  "Presley",
  "Sunny",
  "Indie",
  "Lake",
  "Scout",
  "Lior",
  "Shay",
  "Rene",
  "Aspen",
  "Austen",
  "Dallas",
  "Robin",
  "Kai",
  "Justice",
  "Raine",
  "Emory",
  "Jaden",
  "Milan",
  "Corey",
  "Quincy",
  "Shannon",
  "Tate",
  "Val",
"Wynn",
"Jesse",
"Aiden",
"Jayden",
"Harley",
"Case",
"Row",
"London",
"Gray",
"Sky",
"Paris",
"Brett",
"Zion",
"Noel",
"Sam",
"Lennox",
"Haven",
"Lex",
"Ari",
"Peyton",
"Ocean",
"Hunter",
"Micah",
"Emery",
"Blair",
"Reagan",
"Reign",
"Andi",
"Reed",
"August",
"Ryan",
"Chandler",
"Kit",
"Story",
"Paxton",
"Sage",
"Mackenzie",
"Addison",
"Jade",
"Payton",
"Frankie",
"Reese",
"Rylan",
"Sunny",
"Toby",
"Oak",
"Drew",
"Avery",
"Hollis",
"Elliott",
"Cory",
"Shawn",
"Jessie",
"Rowe",
"Justice",
"Amari",
"Ellery",
"Indigo",
"True",
"Laken",
"Spencer",
"Kasey",
"Mack",
"Gray",
"River",
"Ash",
"Jody",
"Sloan",
"Karter",
"Harley",
"London",
"Sage",
"Reed",
"Eden",
"Jordan",
"Jules",
"Tory",
"Leighton",
"Rory",
"Kendall",
"Terry",
"Blake",
"Sky",
"Wren",
"Darian",
"Dylan",
"Shawn",
"Arlo",
"Brett",
"Chris",
"Jay",
"Reagan",
"Lane",
"Casey",
"Devon",
"Reese",
"Skylar",
"Remy",
"Elliot",
"Drew",
"Cameron",
"Jalen",
"Dallas",
"Corey",
"Rowen",
"Emory",
"Blake",
"Sutton",
"Peyton",
"Jordyn",
"Anderson",
"Oakley",
"Tatum",
"Aiden",
"August",
"Brook",
"Harper",
"Marley",
"Wynn",
"Jade",
"Robin",
"Bailey",
"Shay",
"Riley",
"Morgan",
"Rowan",
"Phoenix",
"Eden",
"Haven",
"Avery",
"Blair",
"Sky",
"Parker",
"Indie",
"Hunter",
"Sage",
"Finley",
"Rain",
"River",
"Ari",
"Cameron",
"Emery",
"Lennon",
"Dakota",
"Remi",
"Elliot",
"Taylor",
"Casey",
"Jordan",
"Rowe",
"Jesse",
"Rylan",
"Reese",
"Peyton",
"Arden",
"Wynn",
"Shiloh",
"Sutton",
"Skylar",
"Tatum",
"Gray",
"Marley",
"Monroe",
"Oakley",
"Blake",
"Aspen",
"Rory",
"Charlie",
"Quinn"
]

  ],
  date: [
    "Movie night at home with popcorn",
    "Picnic under the stars",
    "Cook a new recipe together",
    "Take a sunset walk",
    "Visit a local art gallery",
    "Go bowling",
    "Have a karaoke night",
    "Try a new restaurant",
    "Go stargazing with blankets",
    "Take a dance class together",
    "Make homemade pizza",
    "Go for a scenic drive",
    "Visit a farmer’s market",
    "Play mini golf",
    "Do a wine or beer tasting",
    "Watch a comedy show",
    "Visit an escape room",
    "Go to a live concert",
    "Do a couples’ spa night at home",
    "Have a board game marathon",
    "Try an online painting class",
    "Go roller skating or ice skating",
    "Take a yoga class together",
    "Go to a trivia night",
    "Visit a museum",
    "Try a new dessert café",
    "Watch the sunrise",
    "Build a blanket fort and watch a movie",
    "Go on a photo scavenger hunt",
    "Visit an animal shelter",
    "Rent bikes or scooters",
    "Go hiking",
    "Have a bonfire with marshmallows",
    "Go to a drive-in movie",
    "Visit a botanical garden",
    "Do a puzzle together",
    "Make cocktails or mocktails at home",
    "Go kayaking or paddle boarding",
    "Visit a flea market or thrift shop",
    "Try an escape room online",
    "Write love letters to each other",
    "Visit a rooftop bar",
    "Try a cooking competition at home",
    "Go to a local festival or fair",
    "Volunteer together",
    "Take a pottery or art class",
    "Make sushi together",
    "Visit a planetarium",
    "Go to a sports game",
    "Do a Netflix random pick",
    "Visit a nearby town spontaneously",
    "Have breakfast for dinner",
    "Play video games together",
    "Have a “no phones” night",
    "Go camping or glamping",
    "Recreate your first date",
    "Go on a boat ride",
    "Make vision boards together",
    "Have a themed dinner (Italian, Mexican, etc.)",
    "Watch funny YouTube videos together",
    "Visit an arcade",
    "Try indoor rock climbing", 
    "Attend a poetry reading or open mic",
    "Bake cookies or cupcakes",
    "Go to a local fairground",
    "Take a scenic train ride",
    "Have a “yes day” (say yes to each other’s ideas)",
    "Visit a bookstore and pick books for each other",
    "Go horseback riding",
    "Take a cooking class",
    "Go to a photo booth or take Polaroids",
    "Have a fondue night",
    "Go swimming or to a hot spring",
    "Try a new café and people-watch",
    "Visit a haunted location or ghost tour",
    "Go thrift shopping for funny outfits",
    "Play “Would You Rather?”",
    "Go to the beach at night",
    "Take a scenic walk in nature",
    "Go apple or berry picking",
    "Have a picnic indoors on a rainy day",
    "Watch a live theater performance",
    "Try a food truck crawl",
    "Make breakfast together on a lazy morning",
    "Visit a cat café or dog café",
    "Take a scenic ferry ride",
    "Make your own sundaes",
    "Have a trivia or quiz night",
    "Try a pottery painting studio",
    "Go to a planetarium",
    "Have a candlelit dinner at home",
    "Play “Never Have I Ever”",
    "Go to a rooftop for city views",
    "Try a VR or AR experience",
    "Make a time capsule together",
    "Go to a comedy improv show",
    "Try a mystery dinner",
    "Go ice cream tasting",
    "Visit a seasonal market (Christmas, summer, etc.)",
    "Spend the night at a cozy Airbnb or cabin getaway"
  ],
  movie:[
    "The Shawshank Redemption", 
    "The Dark Knight", 
    "Inception  Titanic", 
    "Avatar", 
    "Forrest Gump", 
    "The Godfather", 
    "The Godfather Part II", 
    "Pulp Fiction", 
    "Fight Club", 
    "The Matrix", 
    "Interstellar", 
    "The Lord of the Rings: The Fellowship of the Ring", 
    "The Lord of the Rings: The Two Towers", 
    "The Lord of the Rings: The Return of the King", 
    "Gladiator", 
    "Saving Private Ryan", 
    "The Green Mile", 
    "Schindler’s List", 
    "Good Will Hunting", 
    "Braveheart", 
    "Jurassic Park", 
    "Star Wars: A New Hope", 
    "Star Wars: The Empire Strikes Back", 
    "Star Wars: Return of the Jedi", 
    "Star Wars: The Force Awakens", 
    "Spider-Man: No Way Home", 
    "Avengers: Endgame", 
    "Avengers: Infinity War", 
    "Iron Man", 
    "Black Panther", 
    "Doctor Strange", 
    "Captain America: Civil War", 
    "Guardians of the Galaxy", 
    "Thor: Ragnarok", 
    "Ant-Man", 
    "Captain Marvel", 
    "Deadpool", 
    "Logan", 
    "X-Men: Days of Future Past", 
    "The Batman", 
    "Joker", 
    "The Dark Knight Rises", 
    "Man of Steel", 
    "Wonder Woman", 
    "Aquaman", 
    "Suicide Squad", 
    "The Flash", 
    "The Hunger Games", 
    "Catching Fire", 
    "Mockingjay Part 1", 
    "Mockingjay Part 2", 
    "Harry Potter and the Sorcerer’s Stone", 
    "Harry Potter and the Chamber of Secrets", 
    "Harry Potter and the Prisoner of Azkaban", 
    "Harry Potter and the Goblet of Fire", 
    "Harry Potter and the Order of the Phoenix", 
    "Harry Potter and the Half-Blood Prince", 
    "Harry Potter and the Deathly Hallows: Part 1", 
    "Harry Potter and the Deathly Hallows: Part 2", 
    "Fantastic Beasts and Where to Find Them", 
    "Fantastic Beasts: The Crimes of Grindelwald", 
    "The Hobbit: An Unexpected Journey",
    "The Hobbit: The Desolation of Smaug",
    "The Hobbit: The Battle of the Five Armies",
    "Pirates of the Caribbean: The Curse of the Black Pearl",
    "Pirates of the Caribbean: Dead Man’s Chest",
    "Pirates of the Caribbean: At World’s End",
    "Pirates of the Caribbean: On Stranger Tides",
    "Pirates of the Caribbean: Dead Men Tell No Tales",
    "The Lion King",
    "Aladdin",
    "Beauty and the Beast",
    "Frozen  Frozen II",
    "Moana  Encanto",
    "Tangled",
    "Zootopia",
    "Coco",
    "Inside Out",
    "Toy Story",
    "Toy Story 2",
    "Toy Story 3",
    "Toy Story 4",
    "Finding Nemo",
    "Finding Dory",
    "Up",
    "Monsters, Inc.",
    "Monsters University",
    "The Incredibles",
    "The Incredibles 2",
    "Ratatouille",
    "Wall-E",
    "Cars",
    "Cars 2",
    "Cars 3",
    "A Bug’s Life",
    "Turning Red",
    "Soul",
    "Luca",
    "Elemental",
    "Shrek",
    "Shrek 2",
    "Shrek the Third",
    "Shrek Forever After",
    "Puss in Boots",
    "Puss in Boots: The Last Wish",
    "Kung Fu Panda",
    "Kung Fu Panda 2",
    "Kung Fu Panda 3",
    "How to Train Your Dragon",
    "How to Train Your Dragon 2",
    "How to Train Your Dragon: The Hidden World",
    "Madagascar",
    "Madagascar: Escape 2 Africa",
    "Madagascar 3: Europe’s Most Wanted",
    "Despicable Me",
    "Despicable Me 2",
    "Despicable Me 3",
    "Minions",
    "Sing",
    "Sing 2",
    "The Secret Life of Pets",
    "The Secret Life of Pets 2",
    "The Super Mario Bros. Movie",
    "The Lego Movie",
    "The Lego Batman Movie",
    "The Lego Movie 2: The Second Part",
    "Spider-Man: Into the Spider-Verse",
    "Spider-Man: Across the Spider-Verse",
    "The Amazing Spider-Man",
    "The Amazing Spider-Man 2",
    "Venom",
    "Venom: Let There Be Carnage",
    "Eternals",
    "Shang-Chi and the Legend of the Ten Rings",
    "Captain America: The First Avenger",
    "Avengers: Age of Ultron",
    "Thor",
    "Hulk",
    "Doctor Strange in the Multiverse of Madness",
    "Guardians of the Galaxy Vol. 3",
    "The Marvels",
    "Oppenheimer",
    "Barbie",
    "Dune",
    "Dune: Part Two",
    "The Revenant",
    "The Wolf of Wall Street",
    "Catch Me If You Can",
    "The Departed",
    "Shutter Island",
    "Inglourious Basterds",
    "Django Unchained",
    "Once Upon a Time in Hollywood",
    "Kill Bill: Vol. 1",
    "Kill Bill: Vol. 2",
    "Reservoir Dogs",
    "No Country for Old Men",
    "There Will Be Blood",
    "American Psycho",
    "Se7en",
    "Gone Girl",
    "The Social Network",
    "The Big Short",
    "Moneyball",
    "Whiplash",
    "La La Land",
    "The Greatest Showman",
    "A Star Is Born",
    "Bohemian Rhapsody",
    "Rocketman  Elvis",
    "Mamma Mia!",
    "Mamma Mia! Here We Go Again",
    "Pitch Perfect",
    "Pitch Perfect 2",
    "Pitch Perfect 3",
    "Mean Girls",
    "Clueless",
    "Legally Blonde",
    "10 Things I Hate About You",
    "The Notebook",
    "The Fault in Our Stars",
    "To All the Boys I’ve Loved Before",
    "Always Be My Maybe",
    "Crazy Rich Asians",
    "Bridesmaids",
    "The Proposal",
    "27 Dresses",
    "Love Actually",
    "Notting Hill",
    "Pretty Woman",
    "Sleepless in Seattle",
    "You’ve Got Mail",
    "While You Were Sleeping",
    "My Best Friend’s Wedding",
    "The Holiday",
    "The Devil Wears Prada",
    "Julie & Julia",
    "Eat Pray Love",
    "Under the Tuscan Sun",
    "500 Days of Summer",
    "About Time",
    "The Time Traveler’s Wife",
    "The Vow",
    "La La Land",
    "The Theory of Everything",
    "A Beautiful Mind",
    "Hidden Figures",
    "The Imitation Game",
    "The Pursuit of Happyness",
    "The Blind Side",
    "Remember the Titans",
    "Coach Carter",
    "Creed",
    "Sleepless in Seattle",
    "You’ve Got Mail",
    "While You Were Sleeping",
    "My Best Friend’s Wedding",
    "The Holiday",
    "The Devil Wears Prada",,
    "Julie & Julia", 
    "Eat Pray Love", 
    "Under the Tuscan Sun", 
    "500 Days of Summer", 
    "About Time", 
    "The Time Traveler’s Wife", 
    "The Vow", 
    "La La Land", 
    "The Theory of Everything", 
    "A Beautiful Mind", 
    "Hidden Figures", 
    "The Imitation Game", 
    "The Pursuit of Happyness", 
    "The Blind Side", 
    "Remember the Titans", 
    "Coach Carter", 
    "Creed", 
    "Creed II", 
    "Rocky", 
    "Rocky II", 
    "Rocky III", 
    "Rocky IV", 
    "Rocky Balboa", 
    "Black Swan", 
    "The Prestige", 
    "Memento", 
    "Tenet", 
    "Oppenheimer", 
    "The Imitation Game", 
    "1917", 
    "Dunkirk", 
    "Midway", 
    "Top Gun", 
    "Top Gun: Maverick", 
    "Mission: Impossible – Fallout", 
    "Mission: Impossible – Dead Reckoning", 
    "John Wick", 
    "John Wick: Chapter 2", 
    "John Wick: Chapter 3 – Parabellum", 
    "John Wick: Chapter 4", 
    "Die Hard", 
    "Die Hard 2", 
    "Die Hard with a Vengeance", 
    "Lethal Weapon", 
    "Bad Boys", 
    "Bad Boys II", 
    "Bad Boys for Life", 
    "Men in Black", 
    "Men in Black II", 
    "Men in Black 3", 
    "Independence Day", 
    "Armageddon", 
    "The Day After Tomorrow", 
    "2012", 
    "San Andreas", 
    "Twister", 
    "Deep Impact", 
    "The Martian", 
    "Gravity", 
    "Arrival", 
    "Contact", 
    "Blade Runner", 
    "Blade Runner 2049", 
    "Ex Machina", 
    "Her", 
    "The Truman Show", 
    "Eternal Sunshine of the Spotless Mind", 
    "The Curious Case of Benjamin Button", 
    "The Sixth Sense", 
    "Signs", 
    "The Others", 
    "Get Out", 
    "Us", 
    "Nope", 
    "A Quiet Place", 
    "A Quiet Place Part II", 
    "The Conjuring", 
    "The Conjuring 2", 
    "Annabelle", 
    "Annabelle: Creation", 
    "The Nun", 
    "The Nun II", 
    "Insidious", 
    "Insidious: Chapter 2", 
    "Insidious: The Red Door", 
    "Paranormal Activity", 
    "It", 
    "It Chapter Two", 
    "The Ring", 
    "The Grudge", 
    "Scream", 
    "Scream 2", 
    "Scream 3", 
    "Scream 4", 
    "Scream (2022)", 
    "Halloween", 
    "Halloween (2018)", 
    "Friday the 13th", 
    "Nightmare on Elm Street", 
    "The Exorcist", 
    "The Shining", 
    "Doctor Sleep", 
    "The Silence of the Lambs", 
    "Hannibal", 
    "Red Dragon", 
    "Seven Pounds", 
    "Collateral", 
    "Heat", 
    "The Irishman", 
    "Goodfellas", 
    "Casino", 
    "Scarface", 
    "The Untouchables", 
    "The Departed", 
    "Training Day", 
    "American Gangster", 
    "The Equalizer", 
    "The Equalizer 2", 
    "The Equalizer 3"
  ],
  bottle: [
    "Do a silly dance",
    "Make your funniest face",
    "Tell a joke",
    "Act like a robot",
    "Sing a line from your favorite song",
    "Spin around three times",
    "Walk like a crab",
    "Do five jumping jacks",
    "Pretend to be a superhero",
    "Make an animal sound",
    "Say the alphabet backward (or try to!)",
    "Share your favorite food",
    "Pretend you’re on a cooking show",
    "Do your best movie villain impression",
    "Name a fruit for every letter you can think of",
    "Say something nice about the person on your left",
    "Say your favorite color without using words",
    "Clap your hands ten times fast",
    "Act like your favorite cartoon character ",
    "Name your favorite ice cream flavor",
    "Balance on one foot for ten seconds",
    "Pretend to be an astronaut",
    "Whistle a tune",
    "Say a tongue twister",
    "Do your best dinosaur roar",
    "Tell everyone what makes you laugh",
    "Pretend to talk to a puppy",
    "Say your name in a funny voice",
    "Share a fun fact you know",
    "Pretend you’re invisible",
    "Say something kind about yourself",
    "Walk in slow motion",
    "Make up a silly rhyme",
    "Act like you’re swimming in the air",
    "Name three animals that live in the ocean",
    "Say one thing you’re grateful for",
    "Do your best happy dance",
    "Spell your name using your elbows",
    "Pretend to be a famous singer",
    "Act like you’re walking on the moon",
    "Say your favorite subject in school",
    "Make a shape with your hands",
    "Pretend you’re a teacher for ten seconds",
    "Name a country you want to visit",
    "Do your favorite dance move",
    "Say a compliment to the group",
    "Pretend to eat your favorite meal",
    "Do your best monster impression",
    "Pretend to sneeze dramatically",
    "Say your favorite animal sound",
    "Make a funny sound effect",
    "Pretend to be a pirate",
    "Say a word in another language",
    "Tell everyone your favorite hobby",
    "Pretend to be a robot with low battery",
    "Spin in place until you get dizzy (safely!)",
    "Say your favorite holiday",
    "Name a planet",
    "Act like a bird trying to fly",
    "Make a heart shape with your hands",
    "Pretend to play an instrument",
    "Say your favorite cartoon",
    "Make your best superhero pose",
    "Pretend you just saw something amazing",
    "Act like a scientist discovering something new",
    "Do a happy cheer",
    "Say your favorite book",
    "Pretend you’re giving a weather report",
    "Say what you want to be when you grow up",
    "Pretend to walk through sticky mud",
    "Share your favorite dessert",
    "Do your best dance move from a movie",
    "Pretend to talk to an alien",
    "Say your favorite game",
    "Act like you’re blowing out candles",
    "Make a silly noise",
    "Pretend to juggle",
    "Say your favorite animal",
    "Do a slow-motion laugh",
    "Act like a rock star",
    "Pretend you’re on a roller coaster",
    "Say something that always makes you smile",
    "Pretend to catch a butterfly",
    "Make a funny hand gesture",
    "Say your favorite song",
    "Act like a famous athlete",
    "Do a superhero landing pose",
    "Pretend to be a statue for five seconds",
    "Say your favorite season",
    "Act like a detective solving a mystery",
    "Do your best chicken dance",
    "Say one thing you love about your family",
    "Pretend you’re driving a race car",
    "Say a silly sentence",
    "Pretend you’re in outer space",
    "Make a funny hat gesture on your head",
    "Say something kind to the person next to you",
    "Pretend you’re flying a kite",
    "Do a silly victory pose",
    "Say what you want to do this weekend",
    "Pretend to be your favorite emoji"
  ],
  truth: [
    "What’s your favorite holiday and why?",
    "Pretend to be a news anchor giving breaking news.",
    "Act like your favorite superhero.",
    "Say three nice things about yourself.",
    "Have you ever had an embarrassing text fail?",
    "Make a silly rhyme about everyone in the room.",
    "Pretend you’re a famous singer.",
    "Who’s the most organized person here?",
    "Try to balance on one leg for 30 seconds.",
    "Have you ever broken a rule at school?",
    "Make up a silly song about your family.",
    "Pretend to drive a race car.",
    "Say something in your most dramatic movie voice.",
    "Pretend you’re an old grandparent telling a story.",
    "Tell a short ghost story dramatically.",
    "What’s your favorite song right now?",
    "Do 10 pushups.",
    "Say the alphabet backward.",
    "What’s your favorite subject in school?",
    "Make a funny commercial about toothpaste.",
    "Pretend you’re an alien visiting Earth.",
    "Who’s your hero?",
    "What’s one thing you can’t live without?",
    "What’s your favorite color?",
    "Pretend you’re asleep and snore loudly.",
    "Who would play you in a movie about your life?",
    "Have you ever peeked at your presents before Christmas?",
    "Act like you’re hosting a reality show.",
    "Try to juggle 3 random objects.",
    "Pretend to be an elephant.",
    "Have you ever pretended to be sick to skip something?",
    "Dance to a made-up song.",
    "Make a fish face.",
    "What’s your most embarrassing childhood memory?",
    "Tell everyone your favorite joke.",
    "Act like a teacher.",
    "What’s your favorite song to sing out loud?",
    "Make a funny commercial about toothpaste.",
    "Pretend you’re an alien visiting Earth.",
    "Who’s your hero?",
    "What’s one thing you can’t live without?",
    "What’s your favorite color?",
    "Pretend you’re asleep and snore loudly.",
    "Who would play you in a movie about your life?",
    "Have you ever peeked at your presents before Christmas?",
    "Act like you’re hosting a reality show.",
    "Try to juggle 3 random objects.",
    "Pretend to be an elephant.",
    "Have you ever pretended to be sick to skip something?",
    "Dance to a made-up song.",
    "Make a fish face.",
    "What’s your most embarrassing childhood memory?",
    "Tell everyone your favorite joke.",
    "Act like a teacher.",
    "What’s your favorite song to sing out loud?",
    "Pretend to be invisible.",
    "Pretend you’re a flight attendant giving safety instructions.",
    "Have you ever had a crush on a teacher?",
    "Do your best villain laugh.",
    "Make a funny face.",
    "What’s your favorite fruit?",
    "What’s your dream job?",
    "Pretend to win an Oscar and give a speech.",
    "If you could live anywhere, where would it be?",
    "Who in the family makes you laugh the most?",
    "Pretend you’re on the moon.",
    "Tell a knock-knock joke.",
    "Speak in song lyrics for one minute.",
    "What’s your favorite book?",
    "Make up a cheer about yourself.",
    "Do 5 jumping jacks.",
    "Pretend you’re swimming underwater.",
    "What’s your favorite movie?",
    "Say one nice thing about everyone here.",
    "Pretend you’re a magician.",
    "Who takes the longest to get ready?",
    "Have you ever forgotten your homework?",
    "Talk like a pirate.",
    "Do your best impression of a teacher.",
    "What’s your favorite ice cream?",
    "Pretend you’re a superhero saving the day.",
    "Sing a verse from your favorite song.",
    "Have you ever lied to your parents?",
    "Do your best animal sound.",
    "Who do you admire most in this room?",
    "Pretend your shoe is a phone and make a call.",
    "Speak like a robot for one minute.",
    "Say your name backward.",
    "What’s your biggest fear?",
    "Pretend you just won a million dollars.",
    "Make up a new dance move.",
    "Do your best TikTok dance.",
    "Do your best chicken dance.",
    "Who’s the funniest person here?",
    "What’s your favorite ice cream?",
    "Pretend you’re a superhero saving the day.",
    "Sing a verse from your favorite song.",
    "Have you ever lied to your parents?",
    "Do your best animal sound.",
    "Who do you admire most in this room?",
    "Pretend your shoe is a phone and make a call.",
    "Speak like a robot for one minute.",
    "Say your name backward.",
    "What’s your biggest fear?",
    "Pretend you just won a million dollars.",
    "Make up a new dance move.",
    "Do your best TikTok dance.",
    "Do your best chicken dance.",
    "Who’s the funniest person here?",
    "Make up a fake commercial for toothpaste.",
    "Who’s your favorite Disney character?",
    "Make everyone laugh without saying a word.",
    "Pretend you’re a waiter taking everyone’s order.",
    "Make a silly sound.",
    "What’s your favorite thing about school?",
    "Try to lick your elbow.",
    "Pretend you’re cooking dinner.",
    "What’s your favorite board game?",
    "Who was your first crush?",
    "Have you ever laughed so hard you cried?",
    "Pretend you’re a robot.",
    "Talk in a British accent for two turns.",
    "Who’s your biggest role model?",
    "Have you ever stayed up past bedtime?",
    "What’s your worst habit?",
    "Tell a short story using only animal sounds.",
    "Make your funniest laugh.",
    "What’s your favorite thing to draw?",
    "Act like your favorite movie character.",
    "Pretend to be a talk show host.",
    "What’s your favorite family tradition?",
    "Post a funny selfie in your group chat.",
    "Have you ever failed a test?",
    "Who’s your best friend?",
    "Say three compliments about yourself.",
    "Pretend you’re a dinosaur.",
    "Make your best scary face.",
    "Do five jumping jacks while shouting “I love my family!”",
    "What’s your dream vacation spot?",
    "Who was your first crush?",
    "Have you ever laughed so hard you cried?",
    "Pretend you’re a robot.",
    "Talk in a British accent for two turns.",
    "Who’s your biggest role model?",
    "Have you ever stayed up past bedtime?",
    "What’s your worst habit?",
    "Tell a short story using only animal sounds.",
    "Make your funniest laugh.",
    "What’s your favorite thing to draw?",
    "Act like your favorite movie character.",
    "Pretend to be a talk show host.",
    "What’s your favorite family tradition?",
    "Post a funny selfie in your group chat.",
    "Have you ever failed a test?",
    "Who’s your best friend?",
    "Say three compliments about yourself.",
    "Pretend you’re a dinosaur.",
    "Make your best scary face.",
    "Do five jumping jacks while shouting “I love my family!”",
    "What’s your dream vacation spot?",
    "Have you ever forgotten your homework?",
    "Try to walk straight after spinning around 10 times.",
    "Pretend to be a cat for one minute.",
    "What’s your favorite TV character?",
    "Pretend to eat a giant hamburger.",
    "Act out your morning routine.",
    "What’s one secret you’ve kept from your parents?",
    "Do your best baby cry.",
    "Say something nice about each person here.",
    "Who tells the funniest jokes?",
    "Talk in rhymes for your next turn.",
    "What’s your favorite snack?",
    "Pretend you’re a ballerina.",
    "What’s your favorite animal?",
    "Have you ever lied to get out of trouble?",
    "What’s your most embarrassing moment ever?",
    "Try to whistle a tune.",
    "If you could swap lives with someone here, who would it be?",
    "What’s your biggest insecurity?",
    "Say everything in a whisper for two rounds.",
    "What’s your happiest memory?",
    "Make your best monster roar.",
    "Make up a funny nickname for everyone here.",
    "Pretend to be a baby.",
    "What’s your favorite food?",
    "Who in this group would survive a zombie apocalypse?",
    "Pretend you’re a robot.",
    "Tell a joke that actually makes people laugh.",
    "What’s your favorite social media app?",
    "Sing everything you say for 30 seconds.",
    "What’s your funniest dream?",
    "Who’s the better cook — mom or dad?",
    "Act like a pirate.",
    "Do your best superhero pose.",
    "If you had a magic lamp, what would you wish for?",
    "Act like a news reporter.",
    "Pretend to play the guitar.",
    "Who’s your favorite teacher?",
    "What’s your favorite game to play outside?",
    "Make a silly face and hold it for 10 seconds.",
    "What’s your guilty pleasure TV show?",
    "Pretend you’re a police officer.",
    "Sing everything you say for 30 seconds.",
    "What’s your funniest dream?",
    "Who’s the better cook — mom or dad?",
    "Act like a pirate.",
    "Do your best superhero pose.",
    "If you had a magic lamp, what would you wish for?",
    "Act like a news reporter.",
    "Pretend to play the guitar.",
    "Who’s your favorite teacher?",
    "What’s your favorite game to play outside?",
    "Make a silly face and hold it for 10 seconds.",
    "What’s your guilty pleasure TV show?",
    "Pretend you’re a police officer.",
    "Who’s your hero?",
    "Make a fish face.",
    "What’s your favorite thing to do on weekends?",
    "Act like you’re giving a motivational speech.",
    "Pretend to be a famous actor.",
    "What’s your favorite ice cream flavor?",
    "What’s one thing you’d change about yourself?",
    "Pretend you’re a flight attendant.",
    "Who’s the most competitive?",
    "Pretend you’re stuck in slow motion.",
    "Sing the chorus of your favorite song.",
    "Pretend you’re asleep and snore loudly.",
    "Who’s your hero?",
    "Make a fish face.",
    "What’s your favorite thing to do on weekends?",
    "Act like you’re giving a motivational speech.",
    "Pretend to be a famous actor.",
    "What’s your favorite ice cream flavor?",
    "What’s one thing you’d change about yourself?",
    "Pretend you’re a flight attendant.",
    "Who’s the most competitive?",
    "Pretend you’re stuck in slow motion.",
    "Sing the chorus of your favorite song.",
    "Pretend you’re asleep and snore loudly.",
    "Who’s your favorite Disney character?",
    "Say something in your most dramatic movie voice.",
    "What’s your favorite hobby?",
    "Speak in slow motion for 30 seconds.",
    "What’s your favorite cartoon?",
    "Make up a rap about your day.",
    "Pretend you’re a lion.",
    "Who do you look up to?",
    "What’s your favorite ice cream flavor?",
    "What’s one thing you’d change about yourself?",
    "Pretend you’re a flight attendant.",
    "Who’s the most competitive?",
    "Pretend you’re stuck in slow motion.",
    "Sing the chorus of your favorite song.",
    "Pretend you’re asleep and snore loudly.",
    "Who’s your favorite Disney character?",
    "Say something in your most dramatic movie voice.",
    "What’s your favorite hobby?",
    "Speak in slow motion for 30 seconds.",
    "What’s your favorite cartoon?",
    "Make up a rap about your day.",
    "Pretend you’re a lion.",
    "Who do you look up to?",
    "Pretend to be a waiter taking everyone’s order.",
    "What’s your favorite subject in school?",
    "Try to make everyone laugh in 30 seconds.",
    "What’s your favorite family vacation memory?",
    "What’s the weirdest food you’ve ever tried?",
    "Walk across the room like a model.",
    "What’s your favorite candy?",
    "Make up a new handshake with someone.",
    "Who’s the most competitive person here?",
    "Pretend you’re cooking dinner.",
    "What’s your favorite animal?",
    "Pretend you’re swimming underwater.",
    "What’s one thing you’re proud of?",
    "Try to lick your elbow.",
    "Do 10 squats while naming animals.",
    "Try to make everyone laugh in 30 seconds.",
    "What’s your favorite family vacation memory?",
    "What’s the weirdest food you’ve ever tried?",
    "Walk across the room like a model.",
    "What’s your favorite candy?",
    "Make up a new handshake with someone.",
    "Who’s the most competitive person here?",
    "Pretend you’re cooking dinner.",
    "What’s your favorite animal?",
    "Pretend you’re swimming underwater.",
    "What’s one thing you’re proud of?",
    "Try to lick your elbow.",
    "Do 10 squats while naming animals.",
    "Pretend to be a robot.",
    "What’s your funniest dream?",
    "Pretend you’re on the moon.",
    "Make up a family cheer.",
    "Pretend you’re an old grandparent telling a story.",
    "Say a tongue twister three times fast.",
    "Tell a knock-knock joke.",
    "Pretend you’re a superhero saving the day.",
    "Say the alphabet backward.",
    "Pretend to play an invisible instrument.",
    "Pretend you’re stuck in slow motion.",
    "Pretend you’re an alien visiting Earth.",
    "Do your best animal impression.",
    "Pretend you just won a million dollars.",
    "Act like your favorite movie character.",
    "Pretend your shoe is a phone and make a call.",
    "Make your best evil laugh.",
    "Pretend you’re brushing your teeth in slow motion.",
    "Say something nice about everyone here.",
    "Act like a pirate.",
    "Do your best villain laugh.",
    "Speak like a robot for one minute.",
    "Pretend to be a news anchor.",
    "Pretend to be a famous actor.",
    "Try to juggle 3 random objects.",
    "Make a silly sound.",
    "Sing everything you say for one minute.",
    "Do your best chicken dance.",
    "Make a fish face.",
    "Pretend to fly like a bird.",
    "Pretend you’re asleep and snore loudly.",
    "Pretend you’re invisible.",
    "Act like a baby.",
    "Pretend to be a frog.",
    "Make your funniest laugh.",
    "Walk like a crab.",
    "Do a silly dance.",
    "Say your name backward.",
    "Pretend to drive a race car.",
    "Hop on one foot.",
    "Do your best superhero pose.",
    "Act like your favorite superhero.",
    "Pretend to be a lion.",
    "Pretend you’re riding a horse.",
    "Pretend you’re a police officer.",
    "Pretend you’re a ninja.",
    "Pretend you’re a dinosaur.",
    "Pretend you’re swimming.",
    "Pretend you’re a magician.",
    "Pretend you’re a teacher.",
    "Pretend you’re asleep and snore loudly.",
    "Pretend you’re on the moon.",
    "Pretend you’re invisible.",
    "Pretend you’re cooking dinner.",
    "Pretend you’re a robot.",
    "Pretend to be an elephant.",
    "Pretend to be an alien visiting Earth.",
    "Pretend you’re an old grandparent telling a story.",
    "Pretend you’re a flight attendant giving safety instructions.",
    "Pretend to be your favorite movie character.",
    "Pretend to be a waiter taking everyone’s order.",
    "Pretend to play an invisible instrument.",
    "Pretend to be a talk show host.",
    "Pretend you’re stuck in slow motion.",
    "Pretend you’re a superhero saving the day.",
    "Pretend to play the guitar.",
    "Pretend to be a cat for one minute.",
    "Pretend to interview yourself as a famous person.",
    "Pretend you’re brushing your teeth in slow motion.",
    "Pretend your shoe is a phone and make a call.",
    "Pretend you just won a million dollars.",
    "Pretend to be a news anchor giving breaking news.",
    "Pretend to win an Oscar and give a speech.",
    "Pretend to be a robot.",
    "Pretend to be a dinosaur.",
    "Pretend you’re cooking dinner.",
    "Pretend to be a lion.",
    "Pretend you’re invisible.",
    "Pretend you’re a ninja.",
    "Pretend you’re a police officer.",
    "Pretend you’re on the moon.",
    "Pretend you’re asleep and snore loudly.",
    "Pretend you’re a magician.",
    "Pretend you’re a superhero saving the day.",
    "Pretend to play an invisible instrument.",
    "Pretend you’re brushing your teeth in slow motion.",
    "Pretend to be a frog.",
    "Pretend you’re a flight attendant giving safety instructions.",
    "Pretend you’re cooking dinner.",
    "Pretend your shoe is a phone and make a call.",
    "Pretend you’re invisible.",
    "Pretend you’re a waiter taking everyone’s order.",
    "Pretend to be a lion.",
    "Pretend you’re a magician.",
    "Pretend to be a talk show host.",
    "Pretend to be your favorite movie character.",
    "Pretend to be an alien visiting Earth.",
    "Pretend to win an Oscar and give a speech.",
    "Pretend you’re stuck in slow motion.",
    "Pretend you’re asleep and snore loudly.",
    "Pretend to play an invisible instrument.",
    "Pretend to be a news anchor giving breaking news.",
    "Pretend you’re brushing your teeth in slow motion.",
    "Pretend you’re a dinosaur.",
    "Pretend to be your favorite movie character.",
    "Pretend to interview yourself as a famous person.",
    "Pretend you’re invisible.",
    "Pretend you’re cooking dinner.",
    "Pretend your shoe is a phone and make a call.",
    "Pretend you’re a waiter taking everyone’s order.",
    "Pretend to play the guitar.",
    "Pretend to win an Oscar and give a speech.",
    "Pretend you’re stuck in slow motion.",
    "Pretend to be a lion.",
    "Pretend you’re asleep and snore loudly.",
    "Pretend to be a frog.",
    "Pretend to be a superhero saving the day.",
    "Pretend you’re a magician.",
    "Pretend to be an alien visiting Earth.",
    "Pretend to be a dinosaur.",
    "Pretend you’re a talk show host.",
    "Pretend you’re a news anchor giving breaking news.",
    "Pretend to play an invisible instrument.",
    "Pretend to be your favorite movie character.",
    "Pretend you’re brushing your teeth in slow motion.",
    "Pretend you’re invisible. ",
    "Pretend to win an Oscar and give a speech.",
    "Pretend you’re stuck in slow motion.",
    "Pretend you’re asleep and snore loudly.",
    "Pretend to be a lion.",
    "Pretend you’re cooking dinner.",
    "Pretend your shoe is a phone and make a call.",
    "Pretend you’re a waiter taking everyone’s order.",
    "Pretend to play the guitar.",
    "Pretend to be a superhero saving the day.",
    "Pretend you’re an alien visiting Earth.",
    "Pretend to be a dinosaur.",
    "Pretend to be a magician.",
    "Pretend to be your favorite movie character.",
    "Pretend to be a frog.",
    "Pretend to win an Oscar and give a speech.",
    "Pretend you’re stuck in slow motion.",
    "Pretend to be a lion.",
    "Pretend to play an invisible instrument.",
    "Pretend to be a talk show host.",
    "Pretend to be your favorite movie character.",
    "Pretend to be a superhero saving the day."
  ],
  dinner:[
    "Spaghetti Bolognese",
    "Chicken Alfredo Pasta",
    "Beef Tacos",
    "Vegetable Stir-Fry",
    "Grilled Salmon with Rice",
    "Homemade Pizza",
    "Chicken Fajitas",
    "Shrimp Scampi",
    "Stuffed Peppers",
    "Teriyaki Chicken Bowl",
    "BBQ Ribs",
    "Lasagna",
    "Chicken Caesar Salad",
    "Pulled Pork Sandwiches",
    "Beef Stroganoff",
    "Thai Green Curry",
    "Sushi Night",
    "Chili Con Carne",
    "Fish and Chips",
    "Burrito Bowls",
    "Chicken Parmesan",
    "Shepherd’s Pie",
    "Veggie Burgers",
    "Pesto Pasta with Cherry Tomatoes",
    "Ramen Noodle Soup",
    "Lemon Garlic Chicken",
    "Grilled Steak with Mashed Potatoes",
    "Cajun Shrimp Tacos",
    "Greek Gyros",
    "Stuffed Shells",
    "Beef and Broccoli",
    "Chicken Fried Rice",
    "Pork Chops with Apples",
    "Vegetarian Curry",
    "Enchiladas",
    "Mac and Cheese",
    "Shrimp Fried Rice",
    "Turkey Meatballs",
    "BBQ Chicken Pizza",
    "Baked Ziti",
    "Crispy Chicken Sandwiches",
    "Falafel Wraps",
    "Beef Burritos",
    "Salmon Tacos",
    "Mushroom Risotto",
    "Sloppy Joes",
    "Veggie Quesadillas",
    "Coconut Chicken Curry",
    "Chicken Noodle Soup",
    "Beef Kebabs",
    "Sweet and Sour Chicken",
    "Pulled Jackfruit Sandwiches",
    "Teriyaki Tofu Bowls",
    "Lamb Chops with Roasted Veggies",
    "Tuna Casserole",
    "Baked Potatoes with Toppings",
    "Stuffed Zucchini Boats",
    "Gnocchi with Cream Sauce",
    "Beef Nachos",
    "Margherita Pizza",
    "Buffalo Chicken Wraps",
    "Fried Rice with Egg and Veggies",
    "Mongolian Beef",
    "Vegetarian Pad Thai",
    "Honey Garlic Chicken",
    "Grilled Pork Tenderloin",
    "Shrimp Tacos",
    "Chicken Enchiladas Verde",
    "Beef Quesadillas",
    "Lentil Soup",
    "Chicken Pot Pie",
    "Seafood Paella",
    "Black Bean Burgers",
    "Steak Fajitas",
    "Butternut Squash Soup",
    "Spaghetti Carbonara",
    "Shrimp and Grits",
    "Taco Salad",
    "Eggplant Parmesan",
    "Grilled Cheese and Tomato Soup",
    "Korean BBQ Beef",
    "Cajun Chicken Pasta",
    "Stuffed Cabbage Rolls",
    "Turkey Chili",
    "Spinach and Feta Stuffed Chicken",
    "Sausage and Peppers",
    "Veggie Buddha Bowl",
    "Crispy Tofu Stir-Fry",
    "Garlic Butter Shrimp",
    "Pork Fried Rice",
    "Chicken Shawarma Bowls",
    "Salmon with Asparagus",
    "Homemade Burgers",
    "Beef Stew",
    "Chicken Tikka Masala",
    "Vegetable Lasagna",
    "Ravioli with Marinara Sauce",
    "BBQ Pulled Chicken Sliders",
    "Lobster Mac and Cheese",
    "Greek Salad with Grilled Chicken",
    "Sausage Alfredo Pasta"
  ],
  workout: [
  "Push-ups",
  "Wide-grip pull-ups",
  "Chin-ups",
  "Bent-over rows",
  "Seated cable rows",
  "Lat pulldowns",
  "Deadlifts",
  "T-bar rows",
  "Barbell curls",
  "Hammer curls",
  "Preacher curls",
  "Tricep dips",
  "Tricep kickbacks",
  "Overhead tricep extensions",
  "Close-grip bench press",
  "Arnold press",
  "Overhead shoulder press",
  "Front raises",
  "Lateral raises",
  "Face pulls",
  "Reverse flys",
  "Shrugs",
  "Rear delt raises",
  "Incline dumbbell press",
  "Flat bench press",
  "Chest flys",
  "Push press",
  "Renegade rows",
  "Plank shoulder taps",
  "Supermans",
  "Farmer’s carry",
  "Battle ropes",
  "Kettlebell swings",
  "Squats",
  "Lunges",
  "Step-ups",
  "Glute bridges",
  "Dead bug",
  "Russian twists",
  "Mountain climbers",
  "Burpees",
  "Jumping jacks",
  "Jump rope",
  "High knees",
  "Wall sit",
  "Calf raises",
  "Side planks",
  "Bicycle crunches",
  "Toe touches",
  "Inchworms",
  "Bear crawls"
  ],
  team: [
   "Two Truths and a Lie", 
   "Office Trivia Challenge", 
   "Human Bingo", 
   "Marshmallow Tower Challenge", 
   "Escape Room Challenge", 
   "The Silent Line-Up", 
   "Blindfold Obstacle Course", 
   "Paper Plane Contest", 
   "Scavenger Hunt", 
   "Personality Swap Game", 
   "Desert Island Scenario", 
   "Memory Wall", 
   "Speed Networking", 
   "Office Charades", 
   "Puzzle Race", 
   "Show and Tell", 
   "Compliment Circle", 
   "Creative Pitch", 
   "Build the Tallest Structure", 
   "Guess Who", 
   "Lip Sync Battle", 
   "Balloon Pop Q&A", 
   "Team Pictionary", 
   "Would You Rather", 
   "Company Values Trivia", 
   "Common Thread", 
   "Mystery Lunch", 
   "Group Storytelling", 
   "Name That Tune", 
   "Office Olympics", 
   "Role Reversal", 
   "Emoji Check-In", 
   "Tower Defense", 
   "Negotiation Game", 
   "Find Someone Who", 
   "Guess the Desk", 
   "Paper Bridge Challenge", 
   "Vision Board Building", 
   "Collaborative Art Mural", 
   "Debating Game", 
   "Flash Improv Scenes", 
   "Team Quiz Show", 
   "Communication Chain", 
   "Time Traveler", 
   "Secret Mission Game", 
   "Bucket List Share", 
   "Build a Story from Random Words", 
   "If I Were the Boss for a Day", 
   "The Gratitude Game", 
   "Rapid Fire Brainstorm", 
   "Mystery Box Challenge"

  ],
  chorus: [
  "Vacuum the living room", 
  "Mop the kitchen floor", 
  "Dust all shelves and surfaces", 
  "Clean the bathroom sink", 
  "Wipe mirrors and windows", 
  "Take out the trash", 
  "Clean out the fridge", 
  "Organize the pantry", 
  "Do a load of laundry", 
  "Fold and put away clothes", 
  "Clean the microwave", 
  "Scrub the shower or bathtub", 
  "Wipe down kitchen counters", 
  "Sweep the front porch", 
  "Change bed sheets", 
  "Water the plants", 
  "Clean pet bowls", 
  "Empty the dishwasher", 
  "Load the dishwasher", 
  "Clean baseboards", 
  "Wipe light switches and doorknobs", 
  "Organize one closet", 
  "Sort the mail and recycle junk", 
  "Vacuum under furniture", 
  "Clean windowsills", 
  "Wipe down appliances", 
  "Clean the oven", 
  "Wash the car", 
  "Declutter the entryway", 
  "Clean out your junk drawer", 
  "Dust ceiling fans", 
  "Take recyclables out", 
  "Clean under the bed", 
  "Wash throw blankets and pillow covers", 
  "Organize the bathroom cabinet", 
  "Disinfect remote controls", 
  "Clean out old food from cupboards", 
  "Wipe down kitchen chairs", 
  "Sweep the garage or balcony", 
  "Replace air fresheners or candles", 
  "Vacuum the stairs", 
  "Clean up backyard or patio", 
  "Organize shoes", 
  "Clean the toilet", 
  "Wipe down doors", 
  "Wash windows", 
  "Clean out the freezer", 
  "Polish furniture", 
  "Wipe down walls", 
  "Clean the laundry area"
  ],
} as const;

export { PRESETS, PRESET_ITEMS };
